[global]
dataFrameSerialization = "legacy"
showWarningOnDirectExecution = false

[server]
port = 8501
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
showErrorDetails = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
showPyplotGlobalUse = false
